from DocumentProcessing.pdf_processing.pdf_processor import SpacyPdfProcessor
from DocumentProcessing.docx_processing.docx_processor import (
    extract_text_from_docx, 
    extract_word_metadata
)
from DocumentProcessing.txt_processing.txt_processor import extract_text_from_txt
from DocumentIndexing.Elastic.IndexSettingsGenerator import *
from config import EMBEDDING_DINENSION
from Utils.common_utils import detect_language, is_valid_arxiv_id, get_arxiv_metadata  

class Document:
    def __init__(self, document_id, document_type):
        self.document_id = document_id #UUID
        self.document_type = document_type #type of the document : Research Paper, Research Book, Article, Personal Document, Other
        self.tags = []
        self.project = []
        self.ElsaticIndexSetting = {}
        self.related_documents = {}
        #self.document_summary_vector = ''
        #self.document_title_vector = ''
            
    def process_document(self):
        raise NotImplementedError("This method should be implemented by subclass.")
    
    def generate_index_settings(self):
        # Test stage,only return base mapping
        if True:
            self.ElsaticIndexSetting = GeneralIndexSettings(EMBEDDING_DINENSION).chunk_level_mapping()

    
class PDFDocument(Document):
    file_type = 'pdf'

    def __init__(self, document_id, file_path, document_type,file_name):
        super().__init__(document_id, document_type)
        self.document_original_name = file_name #original name of the document
        self.file_path = file_path #path to the document in the document bank
        self.total_page_number = 1
        self.document_summary = ''
        self.document_title = ''
        self.metadata = {}
        self.text = ''
        #self.toc = {}
        self.annotation  = '' #annotation of the pdf
        self.language = ''  #language of the document
        self.summary = '' #summary of the document
        self.generated_summary = '' #summary generated by the LLM
        self.notes = [] #list of notes ids attached to this pdf document ,see NoteDocument Class

    def process_document(self):
        processor = SpacyPdfProcessor(self.file_path)
        self.language = processor.language
        self.text = processor.extract_text_from_pdf()
        if is_valid_arxiv_id(self.document_original_name):
            self.metadata = get_arxiv_metadata(self.document_original_name)
        else:
            self.metadata = {'Title':processor.get_title(), 'Authors':[], 'Published':'','Updated':'','Summary':'','Categories':[]}
        self.document_summary = self.metadata.pop('Summary', '')
        self.document_title = self.metadata.get('Title', '')
        #self.toc = extract_toc_from_pdf(self.file_path)
        self.notes = processor.extract_notes_from_pdf()
        self.total_page_number = processor.last

        
        
#WIP
class DOCXDocument(Document):
    file_type = 'docx'

    def __init__(self, document_id, file_path, document_type):
        super().__init__(document_id, file_path, document_type)
        self.metadata = {}
        self.text = ''
        self.language = ''
        

    def process_document(self):
        self.text = extract_text_from_docx(self.file_path)
        self.metadata = extract_word_metadata(self.file_path)
        self.set_language()
        self.total_page_number = len(self.text)

#WIP
class TXTDocument(Document):
    file_type = 'txt'

    def __init__(self, document_id, file_location, document_type):
        super().__init__(document_id, file_location, document_type)
        self.text = ''
        self.language = ''

    def process_document(self):
        self.text = extract_text_from_txt(self.file_path)
        self.language = detect_language(self.text)
        self.set_language()
        self.total_page_number = len(self.text)


class NOTEDocument(Document):
    file_type = 'note'

    def __init__(self, document_id,document_type,attached_documents_ids,note_title,note_text,note_type):
        super().__init__(document_id,document_type)
        self.note_title = note_title
        self.text = note_text
        self.note_type = note_type
        self.attached_documents_ids = attached_documents_ids
        

    def process_document(self):
         raise NotImplementedError('This class does not have a process_document method')
    

class GraphDocument(Document):
    file_type = 'graph'

    def __init__(self, document_id,document_type,attached_documents_ids,graph_data,graph_type):
        #graph_data is a dictionary containing the graph data : {nodes:[],edges:[]}
        #if the graph type is pdf_graph,attached_documents_ids is the document id of the pdf document the graph is attached to
        super().__init__(document_id,document_type)
        self.graph_data = graph_data
        self.graph_type = graph_type
        self.attached_documents_ids = attached_documents_ids

    def process_document(self):
         raise NotImplementedError('This class does not have a process_document method')
    
    